language: go
go:
  - 1.4.2
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/revel/revel/...
  - go get -v github.com/revel/cmd/revel

script:
  - go test github.com/revel/revel

  # Build & run the sample apps
  - revel test github.com/wenjie711/Travis_test
