-- MySQL Script generated by MySQL Workbench
-- 06/04/15 19:47:52
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema qiniu-share
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `qiniu-share` ;
CREATE SCHEMA IF NOT EXISTS `qiniu-share` DEFAULT CHARACTER SET utf8 ;
USE `qiniu-share` ;

-- -----------------------------------------------------
-- Table `qiniu-share`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`role` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`role` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(50) NOT NULL COMMENT '角色名称',
  `desc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '角色说明',
  `permission` TEXT NOT NULL COMMENT '权限列表',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否启用',
  `createtime` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roleid` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `qiniu-share`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`admin` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`admin` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL COMMENT '用户名',
  `password` VARCHAR(32) NOT NULL COMMENT '密码',
  `roleid` INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '角色',
  `email` VARCHAR(40) NULL COMMENT '邮箱',
  `realname` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态 1:允许登陆 0:禁止登陆 ',
  `createtime` DATETIME NOT NULL COMMENT '创建时间',
  `lastlogintime` DATETIME NOT NULL COMMENT '最后登陆时间',
  PRIMARY KEY (`id`),
  INDEX `username` (`username` ASC, `roleid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '管理员表';


-- -----------------------------------------------------
-- Table `qiniu-share`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`category` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '栏目id',
  `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '栏目名称',
  `desc` MEDIUMTEXT NOT NULL COMMENT '描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8
COMMENT = '内容分类表';


-- -----------------------------------------------------
-- Table `qiniu-share`.`sharing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`sharing` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`sharing` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文章id',
  `cid` INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '栏目id category表相对应id',
  `aid` INT(10) UNSIGNED NOT NULL COMMENT '管理员ID 对应发表该文章的管理员',
  `title` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '标题',
  `thumb` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片地址',
  `content` TEXT NOT NULL COMMENT '内容',
  `ispublish` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否发布 0:不发布 1:发布',
  `hits` INT(10) NOT NULL DEFAULT '0' COMMENT '点击数',
  `createtime` DATETIME NOT NULL COMMENT '发布时间',
  `updatetime` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `cid` (`cid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '内容表';


-- -----------------------------------------------------
-- Table `qiniu-share`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`user` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `email` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '电子邮箱',
  `username` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `encrypt` VARCHAR(6) NOT NULL DEFAULT '' COMMENT '随机码',
  `nickname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '昵称',
  `regdate` DATETIME NOT NULL COMMENT '注册时间',
  `lastdate` DATETIME NOT NULL COMMENT '最后登录时间',
  `loginnum` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '登陆次数',
  `islock` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否锁定',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '审核状态 5:用户名已存在;4:拒绝;3:删除:2:忽略;0:未审核;1:通过',
  `createtime` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  INDEX `email` (`email`(20) ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qiniu-share`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`comment` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`comment` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `aid` INT(10) UNSIGNED NOT NULL COMMENT '文章ID',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '回复用户uid',
  `replyid` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '回复的commentID',
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '评论内容',
  `agree` INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '同意',
  `against` INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '反对',
  `ip` VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'IP',
  `createtime` DATETIME NOT NULL COMMENT '时间',
  PRIMARY KEY (`id`),
  INDEX `replyid` (`replyid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '内容评论表';


-- -----------------------------------------------------
-- Table `qiniu-share`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`logs` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`logs` (
  `id` INT(10) UNSIGNED NOT NULL COMMENT '日志id',
  `utype` TINYINT(1) NOT NULL COMMENT '操作者所属：1.管理员 2.用户',
  `uid` INT(10) NOT NULL COMMENT '操作人id',
  `module` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT '' COMMENT '操作的模块',
  `url` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT '' COMMENT '操作对应的url',
  `action` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT '' COMMENT '操作对应的action',
  `ip` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT '0.0.0.0' COMMENT '操作者所在IP',
  `desc` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '操作说明',
  `createtime` DATETIME NOT NULL COMMENT '操作时间',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC, `module` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '后台操作日志表';


-- -----------------------------------------------------
-- Table `qiniu-share`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`organization` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`organization` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会员组id',
  `name` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '用户组名称',
  `desc` VARCHAR(100) NOT NULL COMMENT '描述',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否禁用',
  `createtime` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `status` (`status` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qiniu-share`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`attachment` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`attachment` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件id',
  `sid` INT(10) UNSIGNED NOT NULL,
  `key` VARCHAR(45) NOT NULL COMMENT '对应的存储key',
  `name` VARCHAR(45) NOT NULL COMMENT '显示的文件名',
  `type` VARCHAR(45) NOT NULL,
  `downloads` INT(10) NOT NULL DEFAULT 0 COMMENT '下载次数',
  `createtime` DATETIME NOT NULL COMMENT '创建时间',
  `updatetime` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qiniu-share`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`tag` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`tag` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '标签id',
  `name` VARCHAR(45) NOT NULL COMMENT 'tag名称',
  `count` INT(6) NOT NULL DEFAULT 0 COMMENT '标签下的文章数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qiniu-share`.`sharing_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`sharing_tag` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`sharing_tag` (
  `sid` INT(10) UNSIGNED NOT NULL,
  `tid` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`sid`, `tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qiniu-share`.`user_organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qiniu-share`.`user_organization` ;

CREATE TABLE IF NOT EXISTS `qiniu-share`.`user_organization` (
  `uid` INT(10) UNSIGNED NOT NULL,
  `oid` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`uid`, `oid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
